---
# rbenv
- name: Check rbenv
  tags: rbenv
  shell: "{{ rbenv_bin }}/rbenv --version"
  register: status
  failed_when: status.rc not in [0]
  ignore_errors: True
- name: Install rbenv
  tags: rbenv
  git: repo=https://github.com/sstephenson/rbenv.git
       dest={{ rbenv_home }}
  when: status.rc != 0
- name: Set environment variable  
  tags: rbenv
  lineinfile: dest=~/.bash_profile
              {{ item }}
  with_items:
    - line='# rbenv'
    - line='export PATH="$HOME/.rbenv/bin:$PATH"'
    - line='eval "$(rbenv init -)"'
  when: status.rc != 0
- name: Install rbenv ruby-build
  tags: rbenv
  git: repo=https://github.com/sstephenson/ruby-build.git
       dest="{{ rbenv_home }}/plugins/ruby-build"
  when: status.rc != 0
- name: Install Ruby and set global
  tags: rbenv
  shell: "{{ rbenv_bin }}/rbenv install -v {{ global_ruby_version }} ; {{ rbenv_bin }}/rbenv global {{ global_ruby_version }}"
  when: status.rc != 0

# gems
- name: Install Bundler
  shell: "{{ rbenv_home }}/versions/{{ global_ruby_version }}/bin/gem install bundler"
  tags: gems

# pyenv
- name: Install pyenv
  tags: pyenv
  git: repo=https://github.com/yyuu/pyenv.git
       dest={{ pyenv_home }}
- name: Set environment variable
  tags: pyenv
  lineinfile: dest=~/.bash_profile
              {{ item }}
  with_items:
    - line='# pyenv'
    - line='export PATH="$HOME/.pyenv/bin:$PATH"'
    - line='eval "$(pyenv init -)"'
- name: Install pyenv-virtualenv
  tags: pyenv
  git: repo=https://github.com/yyuu/pyenv-virtualenv.git
       dest={{ pyenv_home }}/plugins/pyenv-virtualenv
- name: Install Python and set global
  tags: pyenv
  shell: "{{ pyenv_bin }}/pyenv install {{ python2 }} ; {{ pyenv_bin }}/pyenv install {{ python3 }} ; {{ pyenv_bin }}/pyenv global {{ python2 }}"

# dotfiles
- name: Install my dotfiles
  git: repo=https://github.com/gosyujin/dotfiles.git
       dest={{ my_repo_home }}/dotfiles
  tags: dotfiles
- name: Source my dotfiles
  shell: "cd {{ my_repo_home}}/dotfiles ; sh replace.sh -n"
  tags: dotfiles
